name: "Hello World"
version: "1.0.1"
slug: "hello_world"
description: "Ein einfaches Hello-World-Add-on mit UI"
startup: services
ingress: true
panel_icon: mdi:emoticon-happy
panel_title: Hello
init: false
homeassistant_api: true
arch:
  - amd64
  - aarch64
  - armv7
ports:
  8080/tcp: null
